---
- name: get hosts facts
  hosts: all
  gather_facts: yes

- name: create aws resources
  hosts: centos
  gather_facts: no
  vars:
    virtualenv: '{{ hostvars[inventory_hostname].ansible_env.HOME }}/.virtualenvs/ansible-aws-resources-env'
  vars_files:
    - vars/aws_credentials.yaml
    - 'vars/aws_tags.yaml'
  tasks:
    - name: init server environment
      include_role:
        name: init_server_environment
    - name: create python environment
      include_role:
        name: create_python_environment
    - name: create ec2 keypair
      import_tasks: tasks/create_ec2_keypair.yaml
      when: need_keypair_created
    - name: import extra aws configuration
      block:
        - name: check aws configuration exists
          stat:
            path: '{{ playbook_dir }}/vars/{{ project | replace(" ", "_") }}_aws_configuration.yaml'
          register: extra_exist
          delegate_to: 127.0.0.1
        - name: import aws configuration
          include_vars:
            file: 'vars/{{ project | replace(" ", "_") }}_aws_configuration.yaml'
          when: extra_exist.stat.exists
    - name: build aws environment
      block:
        - include_role:
            name: create_cloudformation_stack
      vars:
        ansible_python_interpreter: '{{ virtualenv }}/bin/python3'
      environment:
        AWS_ACCESS_KEY_ID: '{{ aws_credential.aws_access_key_id }}'
        AWS_SECRET_ACCESS_KEY: '{{ aws_credential.aws_secret_access_key }}'
        PATH: '{{ virtualenv }}/bin:{{ hostvars[inventory_hostname].ansible_env.PATH }}'