---
- name: get hosts facts
  hosts: all
  gather_facts: yes

- name: create aws resources
  hosts: centos
  gather_facts: no
  vars:
    email_address: creator@example.com
    project: b2b marketplace
    deploy_environment: tst
    virtualenv: '{{ hostvars[inventory_hostname].ansible_env.HOME }}/.virtualenvs/ansible-aws-resources-env'
  vars_files:
    - vars/aws_credentials.yaml
    - 'vars/{{ project | replace(" ", "_") }}_aws_configuration.yaml'
    - 'vars/{{ project | replace(" ", "_") }}_aws_tags.yaml'
  tasks:
    - name: init server environment
      include_role:
        name: init_server_environment
    - name: create python environment
      include_role:
        name: create_python_environment
    - name: build aws environment
      block:
        - include_role:
            name: create_cloudformation_stack
          vars:
            cloudformation_name: '{{ aws_cloudformation }}'
            cloudformation_template: '{{ aws_cloudformation }}.yaml.j2'
            cloudformation_tags: '{{ aws_cloudformation_tags }}'
      vars:
        ansible_python_interpreter: '{{ virtualenv }}/bin/python3'
      environment:
        AWS_ACCESS_KEY_ID: '{{ aws_credential.aws_access_key_id }}'
        AWS_SECRET_ACCESS_KEY: '{{ aws_credential.aws_secret_access_key }}'
        PATH: '{{ virtualenv }}/bin:{{ hostvars[inventory_hostname].ansible_env.PATH }}'