---
- name: run pre-tasks
  block:
    - name: fetch tasks
      fetch:
        src: '{{ hostvars["localhost"]["code"]["local_path"] }}/{{ hostvars["localhost"]["code"]["ansible_pre_task"] }}'
        dest: '/tmp/'
        flat: yes
        fail_on_missing: yes
      run_once: yes
    - name: run tasks
      include_tasks: '/tmp/{{ hostvars["localhost"]["code"]["ansible_pre_task"] }}'
  when: hostvars["localhost"]["code"]["ansible_pre_task"] is defined

- name: create python virtualenv
  pip:
    requirements: '{{ hostvars["localhost"]["code"]["local_path"] }}/requirements.txt'
    virtualenv: '{{ virtualenv }}'
    virtualenv_command: /usr/bin/python3 -m venv
  become: yes

- name: synthesize aws cloudformation template
  command: 'cdk synth "*"'
  args:
    chdir: '{{ hostvars["localhost"]["code"]["local_path"] }}'

- name: deploy stack
  command: 'cdk deploy "*" --require-approval never --outputs-file /tmp/cdk_outputs.json'
  args:
    chdir: '{{ hostvars["localhost"]["code"]["local_path"] }}'

- name: run post-tasks
  block:
    - name: fetch tasks
      fetch:
        src: '{{ hostvars["localhost"]["code"]["local_path"] }}/{{ hostvars["localhost"]["code"]["ansible_post_task"] }}'
        dest: '/tmp/'
        flat: yes
        fail_on_missing: yes
      run_once: yes
    - name: run tasks
      include_tasks: '/tmp/{{ hostvars["localhost"]["code"]["ansible_post_task"] }}'
  when: hostvars["localhost"]["code"]["ansible_post_task"] is defined

- name: save cloudformation outputs
  block:
    - name: store cloudformation outputs local
      fetch:
        src: '/tmp/cdk_outputs.json'
        dest: '/tmp/{{ project | replace(" ", "_") }}_{{ deploy_environment }}_{{ aws_credential.aws_account_id }}.json'
        flat: yes
  always:
    - name: check for cloudformation outputs remote
      stat:
        path: '/tmp/cdk_outputs.json'
      register: file_result
    - name: remove cloudformation outputs remote
      file:
        path: '/tmp/cdk_outputs.json'
        state: absent
      when: file_result.stat.exists