- name: remove exist codes files directory
  file:
    path: '{{ hostvars["localhost"]["code"]["local_path"] }}'
    state: absent
  become: yes

- name: git checkout codes
  git:
    repo: '{{ hostvars["localhost"]["code"]["repo"] }}'
    depth: 1
    version: '{{ hostvars["localhost"]["code"]["branch"] }}'
    dest: '{{ hostvars["localhost"]["code"]["local_path"] }}'
    accept_hostkey: yes
    force: yes

- name: remove useless files
  file:
    path: '{{ hostvars["localhost"]["code"]["local_path"] }}/{{ item }}'
    state: absent
  loop:
    - .git

- name: generate config
  block:
    - name: fetch template from remote
      fetch:
        src: '{{ hostvars["localhost"]["code"]["local_path"] }}/config.yaml.j2'
        dest: '/tmp/'
        flat: yes
        fail_on_missing : yes
      run_once: yes
    - name: upload file to remote
      template:
        src: '/tmp/config.yaml.j2'
        dest: '{{ hostvars["localhost"]["code"]["local_path"] }}/config.yaml'
        force: yes