---
- name: kill running ssh agent
  shell: ps aux | grep [s]sh | awk '{print $2}' | xargs sudo kill -15
  become: yes

- name: start ssh agent
  shell: |
    eval $(ssh-agent -s) > /dev/null
    echo '{"SSH_AUTH_SOCK":"'$SSH_AUTH_SOCK'","SSH_AGENT_PID":"'$SSH_AGENT_PID'"}'
  register: env_vars_stdout

- name: store environment variables
  set_fact:
    env_vars: '{{ env_vars_stdout.stdout }}'

- name: add ssh key
  shell: ssh-add '{{ code.repo_private_key }}'
  environment: '{{ env_vars }}'