---
aws_region: cn-northwest-1
aws_iam_casmart_users: B2B-Casmart
aws_iam_thermofisher_users: B2B-ThermoFisher
aws_s3_config_db_bucket: b2b-config-db-backup
aws_s3_casmart_notification_bucket: b2b-casmart-notification
aws_s3_log_bucket: b2b-log-storage
aws_s3_thermofisher_notification_bucket: b2b-thermofisher-notification