- name: get s3 bucket info
  community.aws.aws_s3_bucket_info:
    name: '{{ s3_bucket_name }}'
    region: '{{ s3_region }}'
  register: result

- name: remove exist s3 bucket
  amazon.aws.s3_bucket:
    name: '{{ s3_bucket_name }}'
    region: '{{ s3_region }}'
    state: absent
    force: yes
  when: result['buckets'] | length > 0 and result['buckets'][0]['name'] is defined and result['buckets'][0]['name'] == s3_bucket_name

- name: create s3 bucket
  amazon.aws.s3_bucket:
    name: '{{ s3_bucket_name }}'
    versioning: yes
    region: '{{ s3_region }}'
    tags:
      '{{ aws_resource_tags }}'

- name: create a directory in bucket
  amazon.aws.aws_s3:
    bucket: '{{ s3_bucket_name }}'
    object: '/{{ item }}/'
    mode: create
    region: '{{ s3_region }}'
  loop: '{{ s3_bucket_directory }}'
  when: s3_bucket_directory is defined and s3_bucket_directory | length > 0