---
- name: ensure dependencies are present
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present
  become: yes

- name: add nodesource apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
    state: present
  become: yes

- name: add nodesource repositories for node.js
  apt_repository:
    repo: '{{ item }}'
    state: present
  loop:
    - 'deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main'
    - 'deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main'
  register: node_repo
  become: yes

- name: update apt cache if repo is added
  apt:
    update_cache: yes
    cache_valid_time: 86400
  become: yes
  when: node_repo.changed

- name: ensure node.js is installed
  apt:
    name: 'nodejs={{ nodejs_version | regex_replace("x", "") }}*'
    state: present
  become: yes