- name: generate cloudformation template
  template:
    src: '{{ cloudformation_template }}'
    dest: '/tmp/{{ cloudformation_name }}.yaml'
    force: yes

- name: create cloudformation stack
  amazon.aws.cloudformation:
    region: '{{ aws_region }}'
    stack_name: '{{ cloudformation_name }}'
    template: '/tmp/{{ cloudformation_name }}.yaml'
    tags:
      '{{ cloudformation_tags }}'
  register: cloudformation_result

- name: save cloudformation output to file
  block:
    - name: save output to file
      copy:
        content: "{{ cloudformation_result.stack_outputs | to_nice_yaml }}"
        dest: '/tmp/cloudformation_output.yaml'
        force: yes
    - name: store file local
      fetch:
        src: '/tmp/cloudformation_output.yaml'
        dest: '/tmp/'
        flat: yes
  always:
    - name: check for file remote
      stat:
        path: '/tmp/cloudformation_output.yaml'
      register: file_result
    - name: remove file remote
      file:
        path: '/tmp/cloudformation_output.yaml'
        state: absent
      when: file_result.stat.exists